### ISSUE TITLE
Bookmarks settings

### ISSUE THREAD

**Issue by staticdev** [darkwizard242/ansible-role-googlechrome#6]
##### SUMMARY
I like this role but maybe it would be possible to get some bookmarks settings from this other role: https://github.com/mlangry/ansible-role-google-chrome

I am particularly interested in showing bookmark bar and importing it as html file. Are you interested in adding this here?

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION
The idea is to have something like:

```yaml
- hosts: servers
  roles:
    - darkwizard242.googlechrome
  vars:
    googlechrome_desired_state: latest
    bookmark_bar:
      show_on_all_tabs: true
    google_chrome_global_bookmarks_file_source: bookmarks.html
    google_chrome_global_preferences:
      import_bookmarks_from_file: "/opt/google/chrome/bookmarks.html"
```
